# Generated by Django 3.2.25 on 2024-10-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customerlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLogin',
            new_name='CustomerSignup',
        ),
    ]
