# Generated by Django 3.2.25 on 2024-10-26 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
