# Generated by Django 3.2.25 on 2024-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSignup',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
